# priklad 4

In [1]:
import pandas as pd
import numpy as np
import multiprocessing as mp
import psutil
import time

/var/folders/fb/xl0hnskx527bfqkv38l3sn7h0000gn/T/ipykernel_3252/3264561981.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
psutil.cpu_count()

10

In [3]:
psutil.virtual_memory()

svmem(total=17179869184, available=7214006272, percent=58.0, used=8842559488, free=176455680, active=7114948608, inactive=7014875136, wired=1727610880)

In [4]:
!pwd

/Users/jiricerny/_Git/_venv/_venv/Pyth3_2024/Day4

In [5]:
#data=pd.read_csv(r'C:\Users\Student\Desktop\Pyth3\labfiles\data\UserLogs\user_logs.csv', low_memory=False)
#reader = pd.read_csv(r'C:\Users\Student\Desktop\Pyth3\labfiles\data\UserLogs\user_logs.csv',chunksize=5)
reader = pd.read_csv(r'/Users/jiricerny/_Git/_venv/_venv/_Pyth3/labfiles/data/UserLogs/user_logs.csv',chunksize=5)

In [6]:
next(reader)

,msno,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs
0,rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=,20150513,0,0,0,0,1,1,280.335
1,rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=,20150709,9,1,0,0,7,11,1658.948
2,yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=,20150105,3,3,0,0,68,36,17364.956
3,yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=,20150306,1,0,1,1,97,27,24667.317
4,yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=,20150501,3,0,0,0,38,38,9649.029

In [7]:
def process_log(chunk):
    group=chunk.groupby(chunk.index, sort=False)
    func={'date':['min', 'max', 'count'],
          'num_25':['sum'],
          'num_50':['sum'],
          'num_75':['sum'],
          'num_985':['sum'],
          'num_100':['sum'],
          'num_unq':['sum'],
          'total_secs':['sum']}
    resp=group.agg(func)
    return resp

In [8]:
size=4e7
print('Size: ', size)
#reader = pd.read_csv(r'C:\Users\Student\Desktop\Pyth3\labfiles\data\UserLogs\user_logs.csv',chunksize=size,index_col=['msno'])
reader = pd.read_csv(r'/Users/jiricerny/_Git/_venv/_venv/_Pyth3/labfiles/data/UserLogs/user_logs.csv',chunksize=size,index_col=['msno'])
start=time.time()
pocet_zaznamu_orig = 0

for i in range(10):
    user_log_chunk=next(reader)
    pocet_zaznamu_orig += len(user_log_chunk)
    if i==0:
        result=process_log(user_log_chunk)
    else:
        #result=result. append(process_log(user_log_chunk))
        result=pd.concat([result, process_log(user_log_chunk)])
    print('Num of rows: ', result.shape[0])
    print('Loop {} : {} secs'.format(i, time.time() - start))
    del(user_log_chunk)
print('Size of result: ', len(result))
print('Pocet_zaznamu_orig: ', pocet_zaznamu_orig)

Size:  40000000.0
Num of rows:  1925303
Loop 0 : 28.607603073120117 secs
Num of rows:  3849608
Loop 1 : 56.54262709617615 secs
Num of rows:  5774168
Loop 2 : 84.61021900177002 secs
Num of rows:  7698020
Loop 3 : 112.26873207092285 secs
Num of rows:  9623341
Loop 4 : 140.58726000785828 secs
Num of rows:  11547939
Loop 5 : 169.35398292541504 secs
Num of rows:  13472137
Loop 6 : 195.64860224723816 secs
Num of rows:  15397016
Loop 7 : 222.30605387687683 secs
Num of rows:  17322397
Loop 8 : 249.34076404571533 secs
Num of rows:  19166671
Loop 9 : 270.94848585128784 secs
Size of result:  19166671
Pocet_zaznamu_orig:  392106543

In [9]:
print('Size of result: ', len(result))

Size of result:  19166671

In [10]:
result.columns

MultiIndex([(      'date',   'min'),
            (      'date',   'max'),
            (      'date', 'count'),
            (    'num_25',   'sum'),
            (    'num_50',   'sum'),
            (    'num_75',   'sum'),
            (   'num_985',   'sum'),
            (   'num_100',   'sum'),
            (   'num_unq',   'sum'),
            ('total_secs',   'sum')],
           )

In [11]:
result.head()

                                                  date                 num_25  \
                                                   min       max count    sum
msno
rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=  20150513  20150715    10     40
yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=  20150105  20170110    65    269
PNxIsSLWOJDCm7pNPFzRO/6Mmg2WeZA2nf6hw6t1x3g=  20151201  20170123    15     15
KXF9c/T66LZIzFq+xS64icWMhDQE6miCZAtdXRjZHX8=  20150803  20170130    20     78
oy2721XIrBu+MEh8XjPTlt5b7gCronoHf/oFN+YwIv8=  20150205  20160726    50    150

                                             num_50 num_75 num_985 num_100  \
                                                sum    sum     sum     sum
msno
rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=      8      5       6      69
yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=    108     72      56    3084
PNxIsSLWOJDCm7pNPFzRO/6Mmg2WeZA2nf6hw6t1x3g=      9      8       4     249
KXF9c/T66LZIzFq+xS64icWMhDQE6miCZAtdXRjZHX8=     27     11      10     233
oy2721XIrBu+MEh8XjPTlt5b7gCronoHf/oFN+YwIv8=     76     68      47    2659

                                             num_unq  total_secs
                                                 sum         sum
msno
rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=      78   20290.035
yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=    2398  818179.921
PNxIsSLWOJDCm7pNPFzRO/6Mmg2WeZA2nf6hw6t1x3g=     229   62361.669
KXF9c/T66LZIzFq+xS64icWMhDQE6miCZAtdXRjZHX8=     310   62085.336
oy2721XIrBu+MEh8XjPTlt5b7gCronoHf/oFN+YwIv8=    1832  625925.513

In [12]:
result.columns =['_'.join(col).strip() for col in result.columns.values]

In [13]:
result.head()

,date_min,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum
msno,,,,,,,,,,
rxIP2f2aN0rYNp+toI0Obt/N/FYQX8hcO1fTmmy2h34=,20150513,20150715,10,40,8,5,6,69,78,20290.035
yxiEWwE9VR5utpUecLxVdQ5B7NysUPfrNtGINaM2zA8=,20150105,20170110,65,269,108,72,56,3084,2398,818179.921
PNxIsSLWOJDCm7pNPFzRO/6Mmg2WeZA2nf6hw6t1x3g=,20151201,20170123,15,15,9,8,4,249,229,62361.669
KXF9c/T66LZIzFq+xS64icWMhDQE6miCZAtdXRjZHX8=,20150803,20170130,20,78,27,11,10,233,310,62085.336
oy2721XIrBu+MEh8XjPTlt5b7gCronoHf/oFN+YwIv8=,20150205,20160726,50,150,76,68,47,2659,1832,625925.513

In [14]:
result.tail()

,date_min,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum
msno,,,,,,,,,,
CzQH4kawK4fk8WLTVA4Nh08Hd5ce2l8Tgtu/hHFsCTA=,20170217,20170217,1,1,0,0,0,10,10,1870.739
KFzaAx7Nk7ROMQA/B4HssFllae/8a/5rqoqBdeYAfTI=,20170216,20170216,1,1,0,0,0,0,1,84.712
BS1wRL5jF6AloFSgvOHap42KomIOWboakt32AxiAmto=,20170217,20170217,1,100,11,4,2,28,131,11828.487
rVVkO1e1yZkUlKy621M70v+gBaK0HCuPrUoea1OsxYo=,20170220,20170220,1,6,2,4,0,15,20,5102.491
AKjgT/J+RyvwdBV8iDKIRcgCZej1AQeJYUdSvpxy2mw=,20170227,20170227,1,32,2,0,1,1,33,1164.510

In [15]:
len(result)

19166671

In [16]:
psutil.virtual_memory()

svmem(total=17179869184, available=9773776896, percent=43.1, used=4284497920, free=4028497920, active=2463121408, inactive=5740920832, wired=1821376512)