In [2]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

/var/folders/fb/xl0hnskx527bfqkv38l3sn7h0000gn/T/ipykernel_12874/3596107838.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
import seaborn as sns

In [7]:
class display(object):
    template = """<div style="float: left; padding: 10px;">
    <p style = 'font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    
    def __init__(self, *a):
        self.args = a
    
    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_())
                        for a in self.args)
    def __repr__(self):
        return '\n\n'.join(a+'\n'+repr(eval(a))
                          for a in self.args)

# priklad

In [8]:
airlines=pd.read_csv(r'/Users/jiricerny/_Git/_venv/_venv/Pyth3_2024/_data/FlightsData/airlines.csv')
airports=pd.read_csv(r'/Users/jiricerny/_Git/_venv/_venv/Pyth3_2024/_data/FlightsData/airports.csv')
flights=pd.read_csv(r'/Users/jiricerny/_Git/_venv/_venv/Pyth3_2024/_data/FlightsData/flights.csv',low_memory=False)

In [9]:
display("airlines.head()","airports.head()","flights.head()")

airlines.head()
  IATA_CODE                 AIRLINE
0        UA   United Air Lines Inc.
1        AA  American Airlines Inc.
2        US         US Airways Inc.
3        F9  Frontier Airlines Inc.
4        B6         JetBlue Airways

airports.head()
  IATA_CODE                              AIRPORT         CITY STATE COUNTRY  \
0       ABE  Lehigh Valley International Airport    Allentown    PA     USA
1       ABI             Abilene Regional Airport      Abilene    TX     USA
2       ABQ    Albuquerque International Sunport  Albuquerque    NM     USA
3       ABR            Aberdeen Regional Airport     Aberdeen    SD     USA
4       ABY   Southwest Georgia Regional Airport       Albany    GA     USA

   LATITUDE  LONGITUDE
0  40.65236  -75.44040
1  32.41132  -99.68190
2  35.04022 -106.60919
3  45.44906  -98.42183
4  31.53552  -84.19447

flights.head()
   YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
0  2015      1    1            4      AS             98      N407AS
1  2015      1    1            4      AA           2336      N3KUAA
2  2015      1    1            4      US            840      N171US
3  2015      1    1            4      AA            258      N3HYAA
4  2015      1    1            4      AS            135      N527AS

  ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  ...  ARRIVAL_TIME  \
0            ANC                 SEA                    5  ...         408.0
1            LAX                 PBI                   10  ...         741.0
2            SFO                 CLT                   20  ...         811.0
3            LAX                 MIA                   20  ...         756.0
4            SEA                 ANC                   25  ...         259.0

   ARRIVAL_DELAY  DIVERTED  CANCELLED  CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
0          -22.0         0          0                  NaN               NaN
1           -9.0         0          0                  NaN               NaN
2            5.0         0          0                  NaN               NaN
3           -9.0         0          0                  NaN               NaN
4          -21.0         0          0                  NaN               NaN

   SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  WEATHER_DELAY
0             NaN            NaN                  NaN            NaN
1             NaN            NaN                  NaN            NaN
2             NaN            NaN                  NaN            NaN
3             NaN            NaN                  NaN            NaN
4             NaN            NaN                  NaN            NaN

[5 rows x 31 columns]

In [10]:
airlines.shape

(14, 2)

In [11]:
airports.shape

(322, 7)

In [12]:
flights.shape

(5819079, 31)

In [13]:
flights.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.732926e+06,5.730032e+06,5.730032e+06,...,5.819079e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335204e+03,9.370158e+00,1.607166e+01,1.357171e+03,...,1.493808e+03,1.476491e+03,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.964233e+02,3.708094e+01,8.895574e+00,4.980094e+02,...,5.071647e+02,5.263197e+02,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.210000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,...,1.110000e+03,1.059000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.520000e+03,1.512000e+03,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.740000e+03,7.000000e+00,1.900000e+01,1.754000e+03,...,1.918000e+03,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.250000e+02,2.400000e+03,...,2.400000e+03,2.400000e+03,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [14]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [15]:
for col in flights.columns:
    print("{} => {}".format(col,len(flights[col].unique())))

YEAR => 1
MONTH => 12
DAY => 31
DAY_OF_WEEK => 7
AIRLINE => 14
FLIGHT_NUMBER => 6952
TAIL_NUMBER => 4898
ORIGIN_AIRPORT => 628
DESTINATION_AIRPORT => 629
SCHEDULED_DEPARTURE => 1321
DEPARTURE_TIME => 1441
DEPARTURE_DELAY => 1218
TAXI_OUT => 185
WHEELS_OFF => 1441
SCHEDULED_TIME => 551
ELAPSED_TIME => 713
AIR_TIME => 676
DISTANCE => 1363
WHEELS_ON => 1441
TAXI_IN => 186
SCHEDULED_ARRIVAL => 1435
ARRIVAL_TIME => 1441
ARRIVAL_DELAY => 1241
DIVERTED => 2
CANCELLED => 2
CANCELLATION_REASON => 5
AIR_SYSTEM_DELAY => 571
SECURITY_DELAY => 155
AIRLINE_DELAY => 1068
LATE_AIRCRAFT_DELAY => 696
WEATHER_DELAY => 633

In [16]:
flights.drop(columns='YEAR',inplace=True)

In [17]:
flights.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,4,US,840,N171US,SFO,CLT,20,18.0,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
flights.CANCELLED.unique()

array([0, 1])

In [19]:
flights.CANCELLATION_REASON.unique()

array([nan, 'A', 'B', 'C', 'D'], dtype=object)

In [20]:
cancelled_reasons = flights.groupby('CANCELLATION_REASON')[['CANCELLED']].count()
cancelled_reasons

                     CANCELLED
CANCELLATION_REASON
A                        25262
B                        48851
C                        15749
D                           22

In [24]:
###
for duvod in flights.CANCELLATION_REASON.unique():
    print('{}: {}'.format(duvod, len(flights[flights.CANCELLATION_REASON == duvod])))

nan: 0
A: 25262
B: 48851
C: 15749
D: 22

In [25]:
cancelled = flights.groupby('CANCELLED')[['CANCELLED']].count()

In [26]:
cancelled

           CANCELLED
CANCELLED
0            5729195
1              89884

In [27]:
cancelled_reasons.CANCELLED.sum()

89884

In [28]:
flights.columns

Index(['MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='object')

In [29]:
arr_delay = [col for col in flights.columns if col.endswith('DELAY')][1:]

In [30]:
arr_delay

['ARRIVAL_DELAY',
 'AIR_SYSTEM_DELAY',
 'SECURITY_DELAY',
 'AIRLINE_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'WEATHER_DELAY']

In [31]:
col_del = arr_delay[1:]
flights.drop(columns=col_del, inplace=True)

In [32]:
flights.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON
0,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,...,169.0,1448,404.0,4.0,430,408.0,-22.0,0,0,NaN
1,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,...,263.0,2330,737.0,4.0,750,741.0,-9.0,0,0,NaN
2,1,1,4,US,840,N171US,SFO,CLT,20,18.0,...,266.0,2296,800.0,11.0,806,811.0,5.0,0,0,NaN
3,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,...,258.0,2342,748.0,8.0,805,756.0,-9.0,0,0,NaN
4,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,...,199.0,1448,254.0,5.0,320,259.0,-21.0,0,0,NaN

In [33]:
late=flights.groupby('MONTH')[['ARRIVAL_DELAY']].sum()
late

       ARRIVAL_DELAY
MONTH
1          2656883.0
2          3391960.0
3          2421650.0
4          1515962.0
5          2196049.0
6          4732115.0
7          3308402.0
8          2321913.0
9          -357046.0
10         -376833.0
11          508966.0
12         2861940.0

In [34]:
late.sort_values('ARRIVAL_DELAY',ascending=False).head()

       ARRIVAL_DELAY
MONTH
6          4732115.0
2          3391960.0
7          3308402.0
12         2861940.0
1          2656883.0

In [35]:
jun = flights[flights['MONTH']==6]

In [36]:
len(jun)

503897

In [37]:
jun.groupby('AIRLINE')[['ARRIVAL_DELAY']].sum().sort_values('ARRIVAL_DELAY',ascending=False)

         ARRIVAL_DELAY
AIRLINE
WN           1153590.0
UA            757652.0
EV            657930.0
OO            409069.0
AA            357243.0
DL            339248.0
NK            331611.0
MQ            231257.0
US            195414.0
F9            154037.0
B6            112279.0
VX             30209.0
HA              5882.0
AS             -3306.0

In [38]:
wndf = jun[jun.AIRLINE == 'WN']
len(wndf)

109776

In [39]:
wndf.groupby('FLIGHT_NUMBER')[['ARRIVAL_DELAY']].sum().sort_values('ARRIVAL_DELAY',ascending=False)

               ARRIVAL_DELAY
FLIGHT_NUMBER
858                   4979.0
1523                  4538.0
829                   4313.0
458                   4249.0
35                    4191.0
...                      ...
622                   -575.0
2609                  -626.0
626                   -668.0
478                   -793.0
604                  -1205.0

[4000 rows x 1 columns]

In [40]:
#axis!!!
mask = np.all([(flights.MONTH==6),(flights.AIRLINE == 'WN'),(flights.FLIGHT_NUMBER == 858)],axis=0)

In [41]:
#
df = flights[mask]
df

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON
2388692,6,1,1,WN,858,N713SW,SMF,BUR,805,802.0,...,54.0,358,905.0,2.0,915,907.0,-8.0,0,0,NaN
2405647,6,2,2,WN,858,N7705A,SMF,BUR,805,801.0,...,55.0,358,904.0,3.0,915,907.0,-8.0,0,0,NaN
2422362,6,3,3,WN,858,N7712G,SMF,BUR,805,801.0,...,51.0,358,903.0,3.0,915,906.0,-9.0,0,0,NaN
2439184,6,4,4,WN,858,N7745A,SMF,BUR,805,802.0,...,58.0,358,911.0,3.0,915,914.0,-1.0,0,0,NaN
2456461,6,5,5,WN,858,N417WN,SMF,BUR,805,802.0,...,54.0,358,907.0,3.0,915,910.0,-5.0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2880219,6,30,2,WN,858,N386SW,LAX,SAT,1220,1257.0,...,176.0,1211,1804.0,4.0,1710,1808.0,58.0,0,0,NaN
2885445,6,30,2,WN,858,N386SW,SAT,DAL,1740,1840.0,...,42.0,248,1931.0,26.0,1840,1957.0,77.0,0,0,NaN
2886956,6,30,2,WN,858,N386SW,DAL,TUL,1915,2032.0,...,43.0,237,2124.0,4.0,2010,2128.0,78.0,0,0,NaN
2888290,6,30,2,WN,858,N386SW,TUL,DEN,2045,2154.0,...,79.0,541,2221.0,7.0,2140,2228.0,48.0,0,0,NaN
2889214,6,30,2,WN,858,N386SW,DEN,SEA,2220,2310.0,...,144.0,1024,43.0,3.0,5,46.0,41.0,0,0,NaN

In [42]:
display('jun','airlines')

jun
         MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
2385615      6    1            1      NK            298      N616NK
2385616      6    1            1      AA           1230      N3EPAA
2385617      6    1            1      DL           2044       N6701
2385618      6    1            1      US            448      N151UW
2385619      6    1            1      F9           1126      N214FR
...        ...  ...          ...     ...            ...         ...
2889507      6   30            2      UA           1180      N65832
2889508      6   30            2      UA           1192      N69839
2889509      6   30            2      UA           1480      N37298
2889510      6   30            2      UA           1637      N35260
2889511      6   30            2      UA           1903      N35271

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
2385615            LAS                 IAH                   10
2385616            SEA                 DFW                   15
2385617            ANC                 SLC                   15
2385618            SLC                 CLT                   15
2385619            LAS                 IAD                   15
...                ...                 ...                  ...
2889507            LAX                 ORD                 2359
2889508            LAX                 IAH                 2359
2889509            PDX                 IAH                 2359
2889510            SEA                 IAH                 2359
2889511            IAH                 SJU                 2359

         DEPARTURE_TIME  ...  AIR_TIME  DISTANCE  WHEELS_ON  TAXI_IN  \
2385615           142.0  ...     149.0      1222      628.0      9.0
2385616            23.0  ...     217.0      1660      612.0      3.0
2385617            11.0  ...     261.0      2125      643.0      8.0
2385618             4.0  ...     202.0      1727      538.0      7.0
2385619            17.0  ...     250.0      2065      740.0      8.0
...                 ...  ...       ...       ...        ...      ...
2889507          2358.0  ...     218.0      1744      547.0      5.0
2889508           129.0  ...     172.0      1379      632.0      7.0
2889509           152.0  ...     214.0      1825      734.0     21.0
2889510            12.0  ...     221.0      1874      605.0     13.0
2889511             7.0  ...     240.0      2007      521.0      5.0

         SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
2385615                500         637.0           97.0         0          0
2385616                610         615.0            5.0         0          0
2385617                652         651.0           -1.0         0          0
2385618                607         545.0          -22.0         0          0
2385619                745         748.0            3.0         0          0
...                    ...           ...            ...       ...        ...
2889507                600         552.0           -8.0         0          0
2889508                520         639.0           79.0         0          0
2889509                608         755.0          107.0         0          0
2889510                609         618.0            9.0         0          0
2889511                534         526.0           -8.0         0          0

         CANCELLATION_REASON
2385615                  NaN
2385616                  NaN
2385617                  NaN
2385618                  NaN
2385619                  NaN
...                      ...
2889507                  NaN
2889508                  NaN
2889509                  NaN
2889510                  NaN
2889511                  NaN

[503897 rows x 25 columns]

airlines
   IATA_CODE                       AIRLINE
0         UA         United Air Lines Inc.
1         AA        American Airlines Inc.
2         US               US Airways Inc.
3         F9        Frontier Airlines Inc.
4         B6               JetBlue Airways
5         OO         Skywest Airlines Inc.
6         AS          Alaska Airlines Inc.
7         NK              Spirit Air Lines
8         WN        Southwest Airlines Co.
9         DL          Delta Air Lines Inc.
10        EV   Atlantic Southeast Airlines
11        HA        Hawaiian Airlines Inc.
12        MQ  American Eagle Airlines Inc.
13        VX                Virgin America

In [43]:
jun_airlines= jun.groupby('AIRLINE')[['ARRIVAL_DELAY']].count()

In [44]:
jun_meskania = pd.merge(jun_airlines, airlines, how='left', left_on='AIRLINE',right_on='IATA_CODE')\
    .drop(columns='IATA_CODE')[['AIRLINE','ARRIVAL_DELAY']]

In [45]:
jun_meskania

                         AIRLINE  ARRIVAL_DELAY
0         American Airlines Inc.          43614
1           Alaska Airlines Inc.          14985
2                JetBlue Airways          22246
3           Delta Air Lines Inc.          76760
4    Atlantic Southeast Airlines          47154
5         Frontier Airlines Inc.           7814
6         Hawaiian Airlines Inc.           6663
7   American Eagle Airlines Inc.          23991
8               Spirit Air Lines           9325
9          Skywest Airlines Inc.          49058
10         United Air Lines Inc.          44745
11               US Airways Inc.          33889
12                Virgin America           5227
13        Southwest Airlines Co.         107376

In [46]:
from_to = ['MONTH','DAY','AIRLINE','ORIGIN_AIRPORT','DESTINATION_AIRPORT']
what = ['AIRLINE','ORIGIN_AIRPORT','DESTINATION_AIRPORT','ARRIVAL_DELAY']
flights.groupby(from_to)[what].sum()

                                                                           AIRLINE  \
MONTH DAY AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
1     1   AA      ABQ            DFW                                      AAAAAAAA
                  ATL            DFW                          AAAAAAAAAAAAAAAAAAAA
                                 MIA                                        AAAAAA
                  AUS            DFW                  AAAAAAAAAAAAAAAAAAAAAAAAAAAA
                                 JFK                                            AA
...                                                                            ...
12    31  WN      TUS            DEN                                          WNWN
                                 LAS                                        WNWNWN
                                 LAX                                          WNWN
                                 MDW                                            WN
                                 SAN                                        WNWNWN

                                                                                  ORIGIN_AIRPORT  \
MONTH DAY AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
1     1   AA      ABQ            DFW                                                ABQABQABQABQ
                  ATL            DFW                              ATLATLATLATLATLATLATLATLATLATL
                                 MIA                                                   ATLATLATL
                  AUS            DFW                  AUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUS
                                 JFK                                                         AUS
...                                                                                          ...
12    31  WN      TUS            DEN                                                      TUSTUS
                                 LAS                                                   TUSTUSTUS
                                 LAX                                                      TUSTUS
                                 MDW                                                         TUS
                                 SAN                                                   TUSTUSTUS

                                                                             DESTINATION_AIRPORT  \
MONTH DAY AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
1     1   AA      ABQ            DFW                                                DFWDFWDFWDFW
                  ATL            DFW                              DFWDFWDFWDFWDFWDFWDFWDFWDFWDFW
                                 MIA                                                   MIAMIAMIA
                  AUS            DFW                  DFWDFWDFWDFWDFWDFWDFWDFWDFWDFWDFWDFWDFWDFW
                                 JFK                                                         JFK
...                                                                                          ...
12    31  WN      TUS            DEN                                                      DENDEN
                                 LAS                                                   LASLASLAS
                                 LAX                                                      LAXLAX
                                 MDW                                                         MDW
                                 SAN                                                   SANSANSAN

                                                      ARRIVAL_DELAY
MONTH DAY AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
1     1   AA      ABQ            DFW                           66.0
                  ATL            DFW                           85.0
                                 MIA                          -42.0
                  AUS            DFW                           -6.0
                                 JFK                            0.0
...                                                             ...
12    31  WN      TUS            DEN                          -35.0
                                 LAS                          141.0
                                 LAX                           46.0
                                 MDW                          -29.0
                                 SAN                          -15.0

[2024787 rows x 4 columns]

In [48]:
jun

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON
2385615,6,1,1,NK,298,N616NK,LAS,IAH,10,142.0,...,149.0,1222,628.0,9.0,500,637.0,97.0,0,0,NaN
2385616,6,1,1,AA,1230,N3EPAA,SEA,DFW,15,23.0,...,217.0,1660,612.0,3.0,610,615.0,5.0,0,0,NaN
2385617,6,1,1,DL,2044,N6701,ANC,SLC,15,11.0,...,261.0,2125,643.0,8.0,652,651.0,-1.0,0,0,NaN
2385618,6,1,1,US,448,N151UW,SLC,CLT,15,4.0,...,202.0,1727,538.0,7.0,607,545.0,-22.0,0,0,NaN
2385619,6,1,1,F9,1126,N214FR,LAS,IAD,15,17.0,...,250.0,2065,740.0,8.0,745,748.0,3.0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889507,6,30,2,UA,1180,N65832,LAX,ORD,2359,2358.0,...,218.0,1744,547.0,5.0,600,552.0,-8.0,0,0,NaN
2889508,6,30,2,UA,1192,N69839,LAX,IAH,2359,129.0,...,172.0,1379,632.0,7.0,520,639.0,79.0,0,0,NaN
2889509,6,30,2,UA,1480,N37298,PDX,IAH,2359,152.0,...,214.0,1825,734.0,21.0,608,755.0,107.0,0,0,NaN
2889510,6,30,2,UA,1637,N35260,SEA,IAH,2359,12.0,...,221.0,1874,605.0,13.0,609,618.0,9.0,0,0,NaN
2889511,6,30,2,UA,1903,N35271,IAH,SJU,2359,7.0,...,240.0,2007,521.0,5.0,534,526.0,-8.0,0,0,NaN

In [49]:
from_to[1:]

['DAY', 'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT']

In [58]:
what = 'ARRIVAL_DELAY'

In [59]:
jun.groupby(from_to[1:])[what].sum()

DAY  AIRLINE  ORIGIN_AIRPORT  DESTINATION_AIRPORT
1    AA       ABQ             DFW                    -44.0
              ATL             DFW                   -134.0
                              LAX                    -38.0
                              MIA                     10.0
                              ORD                     -8.0
                                                     ...
30   WN       TUS             DEN                     19.0
                              LAS                      0.0
                              LAX                     27.0
                              MDW                     59.0
                              SAN                     -4.0
Name: ARRIVAL_DELAY, Length: 170288, dtype: float64

In [63]:
junFinal = jun.groupby(from_to[1:])[what].sum().sort_values(ascending=False).reset_index()
junFinal

        DAY AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT  ARRIVAL_DELAY
0         1      UA            ORD                 LGA         2037.0
1        15      UA            ORD                 SFO         1954.0
2        17      AA            ORD                 DFW         1872.0
3        15      DL            MSP                 ORD         1815.0
4        15      DL            ORD                 ATL         1703.0
...     ...     ...            ...                 ...            ...
170283    7      AA            LGA                 MIA         -379.0
170284    9      AA            LGA                 ORD         -382.0
170285   10      AA            LGA                 DFW         -427.0
170286    2      AA            LGA                 DFW         -428.0
170287    7      DL            LGA                 ATL         -433.0

[170288 rows x 5 columns]

In [64]:
#sufixes prejmenuje stejne promenne na ruzne nazvy misto aby pouyil x a y
finalData=pd.merge(junFinal,airlines,how='left',left_on='AIRLINE',right_on='IATA_CODE', suffixes=["_JUN",""]).\
drop(columns='IATA_CODE').\
merge(airports,how='left',left_on='ORIGIN_AIRPORT',right_on='IATA_CODE').\
merge(airports,how='left',left_on='DESTINATION_AIRPORT',right_on='IATA_CODE', suffixes=["_FROM","_TO"])
finalData.head()

,DAY,AIRLINE_JUN,ORIGIN_AIRPORT,DESTINATION_AIRPORT,ARRIVAL_DELAY,AIRLINE,IATA_CODE_FROM,AIRPORT_FROM,CITY_FROM,STATE_FROM,COUNTRY_FROM,LATITUDE_FROM,LONGITUDE_FROM,IATA_CODE_TO,AIRPORT_TO,CITY_TO,STATE_TO,COUNTRY_TO,LATITUDE_TO,LONGITUDE_TO
0,1,UA,ORD,LGA,2037.0,United Air Lines Inc.,ORD,Chicago O'Hare International Airport,Chicago,IL,USA,41.97960,-87.90446,LGA,LaGuardia Airport (Marine Air Terminal),New York,NY,USA,40.77724,-73.87261
1,15,UA,ORD,SFO,1954.0,United Air Lines Inc.,ORD,Chicago O'Hare International Airport,Chicago,IL,USA,41.97960,-87.90446,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484
2,17,AA,ORD,DFW,1872.0,American Airlines Inc.,ORD,Chicago O'Hare International Airport,Chicago,IL,USA,41.97960,-87.90446,DFW,Dallas/Fort Worth International Airport,Dallas-Fort Worth,TX,USA,32.89595,-97.03720
3,15,DL,MSP,ORD,1815.0,Delta Air Lines Inc.,MSP,Minneapolis-Saint Paul International Airport,Minneapolis,MN,USA,44.88055,-93.21692,ORD,Chicago O'Hare International Airport,Chicago,IL,USA,41.97960,-87.90446
4,15,DL,ORD,ATL,1703.0,Delta Air Lines Inc.,ORD,Chicago O'Hare International Airport,Chicago,IL,USA,41.97960,-87.90446,ATL,Hartsfield-Jackson Atlanta International Airport,Atlanta,GA,USA,33.64044,-84.42694

In [65]:
finalData.columns

Index(['DAY', 'AIRLINE_JUN', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'ARRIVAL_DELAY', 'AIRLINE', 'IATA_CODE_FROM', 'AIRPORT_FROM',
       'CITY_FROM', 'STATE_FROM', 'COUNTRY_FROM', 'LATITUDE_FROM',
       'LONGITUDE_FROM', 'IATA_CODE_TO', 'AIRPORT_TO', 'CITY_TO', 'STATE_TO',
       'COUNTRY_TO', 'LATITUDE_TO', 'LONGITUDE_TO'],
      dtype='object')

In [66]:
valid_cols=['DAY', 'ARRIVAL_DELAY', 'AIRLINE', 'AIRPORT_FROM',
       'CITY_FROM', 'STATE_FROM', 'LATITUDE_FROM',
       'LONGITUDE_FROM', 'AIRPORT_TO', 'CITY_TO', 'STATE_TO',
       'LATITUDE_TO', 'LONGITUDE_TO']

In [67]:
finalData=finalData[valid_cols]

In [68]:
finalData.head()

,DAY,ARRIVAL_DELAY,AIRLINE,AIRPORT_FROM,CITY_FROM,STATE_FROM,LATITUDE_FROM,LONGITUDE_FROM,AIRPORT_TO,CITY_TO,STATE_TO,LATITUDE_TO,LONGITUDE_TO
0,1,2037.0,United Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,LaGuardia Airport (Marine Air Terminal),New York,NY,40.77724,-73.87261
1,15,1954.0,United Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,San Francisco International Airport,San Francisco,CA,37.61900,-122.37484
2,17,1872.0,American Airlines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,Dallas/Fort Worth International Airport,Dallas-Fort Worth,TX,32.89595,-97.03720
3,15,1815.0,Delta Air Lines Inc.,Minneapolis-Saint Paul International Airport,Minneapolis,MN,44.88055,-93.21692,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446
4,15,1703.0,Delta Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,Hartsfield-Jackson Atlanta International Airport,Atlanta,GA,33.64044,-84.42694

In [69]:
finalData.shape

(170288, 13)

In [75]:
#engine=create_engine("mysql://root:root@10.2.120.20/jiri")
engine = create_engine("mysql://root:root@127.0.0.1:8890/jiri")

In [76]:
finalData.to_sql(con=engine,name='flights_data',if_exists='replace')

170288

In [77]:
finalData.to_csv(r'/Users/jiricerny/_Git/_venv/_venv/Pyth3_2024/_data/FlightsData/flights_data.csv', sep=";")

In [1]:
import pandas as pd
from sqlalchemy import create_engine

/var/folders/fb/xl0hnskx527bfqkv38l3sn7h0000gn/T/ipykernel_13878/759018811.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
#engine = create_engine("mysql://root:root@10.2.120.20/jiri")
engine = create_engine("mysql://root:root@127.0.0.1:8890/jiri")

In [3]:
data = pd.read_sql_table(con=engine,table_name='flights_data')

In [4]:
data.head()

,index,DAY,ARRIVAL_DELAY,AIRLINE,AIRPORT_FROM,CITY_FROM,STATE_FROM,LATITUDE_FROM,LONGITUDE_FROM,AIRPORT_TO,CITY_TO,STATE_TO,LATITUDE_TO,LONGITUDE_TO
0,0,1,2037.0,United Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,LaGuardia Airport (Marine Air Terminal),New York,NY,40.77724,-73.87261
1,1,15,1954.0,United Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,San Francisco International Airport,San Francisco,CA,37.61900,-122.37484
2,2,17,1872.0,American Airlines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,Dallas/Fort Worth International Airport,Dallas-Fort Worth,TX,32.89595,-97.03720
3,3,15,1815.0,Delta Air Lines Inc.,Minneapolis-Saint Paul International Airport,Minneapolis,MN,44.88055,-93.21692,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446
4,4,15,1703.0,Delta Air Lines Inc.,Chicago O'Hare International Airport,Chicago,IL,41.97960,-87.90446,Hartsfield-Jackson Atlanta International Airport,Atlanta,GA,33.64044,-84.42694